FROM node:16
ARG PORT=1337
ARG BLOCKFROST_PROJECT_ID=''
ENV PORT ${PORT}
ENV BLOCKFROST_PROJECT_ID ${BLOCKFROST_PROJECT_ID}
WORKDIR /app
COPY . .
RUN npm install
EXPOSE ${PORT}
ENTRYPOINT [ "npm", "start" ]